#!/usr/bin/env python
"""
Django settings for garelabo_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# このプロジェクトのルートディレクトリ（manage.py がある場所）を指します
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Djangoプロジェクト固有の秘密鍵です。本番環境では外部に漏らさないでください。
SECRET_KEY = "django-insecure-@4*bvgd%$*ks2(7k3_bw@v(2%xj3_#$^(!2@xr_kag0t^q%ne#"

# SECURITY WARNING: don't run with debug turned on in production!
# デバッグモード。開発中は True にしてエラー詳細を表示し、本番環境では False にします。
DEBUG = True

# サーバーを公開する（本番環境の）ドメイン名やIPアドレスを指定します。
ALLOWED_HOSTS = []


# Application definition
# このDjangoプロジェクトにインストールされているアプリの一覧です。
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# リクエストとレスポンスの間で実行される処理（ミドルウェア）です。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# このプロジェクトのメインとなるURL設定ファイル（urls.py）の場所を指定します。
# (前回のエラー箇所)
ROOT_URLCONF = 'config.urls'

# テンプレート（HTMLファイル）に関する設定です。
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI (Web Server Gateway Interface) アプリケーションの場所を指定します。
# (★ここが修正点です)
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# データベースの接続設定です。
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# パスワードの強度を検証するためのルールです。
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 言語設定（例: 日本語にする場合は 'ja'）
LANGUAGE_CODE = "en-us"

# タイムゾーン（例: 日本時間にする場合は 'Asia/Tokyo'）
TIME_ZONE = "UTC"

# 国際化（翻訳機能）を有効にするか
USE_I18N = True

# タイムゾーンを有効にするか
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# CSS、JavaScript、画像などの静的ファイル（staticファイル）のURLプレフィックスです。
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# モデルの主キー（ID）に自動的に使われるフィールドの型です。
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"