#!/usr/bin/env python
"""
Django settings for garelabo_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # ★ 1. os をインポート
import environ # ★ 2. environ をインポート

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# このプロジェクトのルートディレクトリ（manage.py がある場所）を指します
BASE_DIR = Path(__file__).resolve().parent.parent

# --- ★ 3. environ の設定を追加 ---
env = environ.Env()
# .env ファイルを読み込む (BASE_DIR 直下に .env がある前提)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# ---

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# .env ファイルから読み込むように変更 (推奨)
SECRET_KEY = env('SECRET_KEY', default="django-insecure-@4*bvgd%$*ks2(7k3_bw@v(2%xj3_#$^(!2@xr_kag0t^q%ne#")

# SECURITY WARNING: don't run with debug turned on in production!
# デバッグモード。
DEBUG = env.bool('DEBUG', default=True)

# サーバーを公開する（本番環境の）ドメイン名やIPアドレスを指定します。
ALLOWED_HOSTS = []


# Application definition
# このDjangoプロジェクトにインストールされているアプリの一覧です。
INSTALLED_APPS = [
    # "django.contrib.admin", # ★ 4. adminは不要なためコメントアウト
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # appsをアプリとして設定
    'api_app.apps.ApiAppConfig',

    # サードパーティ製アプリ
    'rest_framework',
    'corsheaders',
]

# リクエストとレスポンスの間で実行される処理（ミドルウェア）です。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    
    "corsheaders.middleware.CorsMiddleware", # ★ 5. CORSミドルウェアを追加
    
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# このプロジェクトのメインとなるURL設定ファイル（urls.py）の場所を指定します。
ROOT_URLCONF = 'config.urls'

# テンプレート（HTMLファイル）に関する設定です。
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI (Web Server Gateway Interface) アプリケーションの場所を指定します。
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# データベースの接続設定です。
# ★ 6. DATABASES 設定を .env から読み込むように変更
DATABASES = {
    # .env ファイルから "DATABASE_URL" という名前の変数を読み込む
    "default": env.db()
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i1n/
LANGUAGE_CODE = "ja" # (日本語に変更)
TIME_ZONE = "Asia/Tokyo" # (日本時間に変更)
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------
# ★ 7. カスタムUserモデルの指定 (これはOK)
# -----------------------------------------------------------------
AUTH_USER_MODEL = 'api_app.User'

# -----------------------------------------------------------------
# ★ 8. メディアファイル (ImageField) の設定 (追記)
# -----------------------------------------------------------------
# ユーザーがアップロードしたファイル (media/) へのURL
MEDIA_URL = '/media/'
# ユーザーがアップロードしたファイルを保存する実際のフォルダの場所
# (C:\garelabo_project\media フォルダを指す)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -----------------------------------------------------------------
# ★ 9. CORS (django-cors-headers) の設定 (追記)
# -----------------------------------------------------------------
# (例) React (localhost:3000) や Vue (localhost:5173) からのアクセスを許可
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]
# (開発中、すべて許可する場合)
# CORS_ALLOW_ALL_ORIGINS = True