# Generated by Django 5.2.8 on 2025-11-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcustom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
