# Generated by Django 5.2.8 on 2025-11-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_savedcustom_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedcustom",
            name="aero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.aero",
            ),
        ),
        migrations.AlterField(
            model_name="savedcustom",
            name="bumper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.bumper",
            ),
        ),
        migrations.AlterField(
            model_name="savedcustom",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.color",
            ),
        ),
        migrations.AlterField(
            model_name="savedcustom",
            name="light",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.light",
            ),
        ),
        migrations.AlterField(
            model_name="savedcustom",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="savedcustom",
            name="wheel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api_app.wheel",
            ),
        ),
    ]
