# Generated by Django 5.2.8 on 2025-11-27 01:27

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0004_alter_savedcustom_aero_alter_savedcustom_bumper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedcustom",
            name="preview_image_url",
            field=models.ImageField(upload_to=api_app.models.user_preview_path),
        ),
    ]
