# Generated by Django 5.2.8 on 2025-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0005_alter_savedcustom_preview_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="rotation_image_folder",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
