# Generated by Django 5.2.8 on 2026-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0006_color_rotation_image_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="name_en",
            field=models.CharField(default="Rocky", max_length=100),
        ),
    ]
