# Generated by Django 5.2.8 on 2026-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0007_vehicle_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedcustom",
            name="preview_image_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
